import { useState } from 'react'
import Head from 'next/head'

const G='#1B7A68', BG='#F6F3EC', TX='#1C1B1F', MU='#5A5857', BD='#E2DDD6'
const SOURCES={
 ftc:{label:'FTC Endorsement Guides',href:'https://www.ftc.gov/business-guidance/advertising-marketing/endorsements-influencers-reviews'},
 copyright:{label:'U.S. Copyright Office AI initiative',href:'https://www.copyright.gov/ai/'},
 nofakes:{label:'Congress.gov — H.R. 2794 (introduced)',href:'https://www.congress.gov/bill/119th-congress/house-bill/2794'},
 ca:{label:'California AB 2602',href:'https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB2602'},
 tn:{label:'Tennessee ELVIS Act',href:'https://www.capitol.tn.gov/Bills/113/Bill/SB2096.pdf'},
 eu:{label:'EU AI Act — EUR-Lex',href:'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02024R1689-20260727'}
}
const AUDIT={
 influencer:{title:'Influencer / creator partnerships',priority:'Medium',issue:'Material connections and endorsement claims need clear, conspicuous disclosure. AI use may add deception or substantiation questions, but there is no blanket FTC rule requiring every AI-assisted post to carry an “AI-generated” label.',next:'Map each material connection, claim, platform format, and approval responsibility. Review disclosures in context.',sources:['ftc']},
 'ai-content':{title:'AI-generated or materially altered content',priority:'High',issue:'AI use can create deception, substantiation, copyright, contract, and provenance questions. Copyrightability depends on the human-authored expression and facts—not a categorical “AI music is never copyrightable” rule.',next:'Record tools, inputs, permissions, human contributions, edits, and review decisions. Escalate material consumer-facing simulations or claims.',sources:['copyright','ftc']},
 music:{title:'Licensed or AI-assisted music',priority:'Medium',issue:'Rights depend on the source material, licenses, human authorship, performer permissions, and distribution terms. Tool output alone does not establish clearance.',next:'Keep licenses and provenance records; review composition, recording, voice, publicity, and contract rights for the intended territory and media.',sources:['copyright','nofakes']},
 synthetic:{title:'Synthetic media / digital replicas',priority:'High',issue:'Digital replicas can implicate state likeness and contract rules. California AB 2602 and Tennessee’s ELVIS Act are enacted state measures; the federal NO FAKES Act cited here remains introduced legislation.',next:'Obtain specific written authorization covering the person, replica, uses, media, term, territory, edits, and revocation or termination terms.',sources:['ca','tn','nofakes']},
 ugc:{title:'User-generated content',priority:'Lower',issue:'UGC may still carry endorsement, license, privacy, likeness, and provenance issues. Brand knowledge and control matter; the label “UGC” is not a safe harbor.',next:'Use submission terms, permission records, moderation, and a documented review path for synthetic or sponsored content.',sources:['ftc','copyright']},
 celebrity:{title:'Celebrity likeness or partnership',priority:'High',issue:'Publicity, contract, false endorsement, and digital-replica rules vary by jurisdiction and use. Perceived permission is not authorization.',next:'Confirm identity-specific permissions and intended uses in writing, then obtain jurisdiction-specific review before release.',sources:['ca','tn','nofakes']},
 'film-tv':{title:'Film or TV content integration',priority:'Lower',issue:'Licenses may need to cover clips, music, performers, marks, edits, synthetic elements, and promotional reuse. A general integration license may not cover every asset.',next:'Create an asset-by-asset rights ledger and compare granted rights with channels, territories, term, edits, and AI-assisted uses.',sources:['copyright']},
 virtual:{title:'Virtual influencer or avatar',priority:'High',issue:'A virtual persona can create endorsement, deception, IP, privacy, and transparency questions. The EU AI Act has phased obligations; applicability and timing require case-specific analysis.',next:'Disclose the nature of the persona where omission could mislead, document its operators and claims, and obtain counsel for applicable markets.',sources:['ftc','eu']}
}
const color={High:['#FCEBEB','#A32D2D'],Medium:['#FAEEDA','#854F0B'],Lower:['#EAF3DE','#3B6D11']}
export default function Home(){
 const [industry,setIndustry]=useState(''),[desc,setDesc]=useState(''),[checked,setChecked]=useState([]),[results,setResults]=useState(null)
 const toggle=k=>setChecked(v=>v.includes(k)?v.filter(x=>x!==k):[...v,k])
 const run=()=>setResults(checked.length?checked.map(k=>AUDIT[k]):[{title:'No activation type selected',priority:'Lower',issue:'No issue-specific screening was performed. A low-priority display is not a finding that the campaign is compliant or risk-free.',next:'Select every applicable activation type and obtain matter-specific review before launch.',sources:['ftc','copyright']}])
 const clear=()=>{setIndustry('');setDesc('');setChecked([]);setResults(null)}
 return <><Head><title>Culture Governance Issue-Spotter — Aloha AI Consulting</title><meta name="description" content="A browser-local issue-spotting checklist for cultural and AI-enabled campaigns, with official sources and clear limitations."/><meta name="robots" content="index, follow"/><link rel="canonical" href="https://aloha-governance-audit.vercel.app/"/><meta property="og:title" content="Culture Governance Issue-Spotter"/><meta property="og:description" content="Informational, browser-local governance issue spotting with official source links."/><meta property="og:type" content="website"/></Head>
 <header><div><strong>Aloha AI Consulting</strong><span>Culture Governance Issue-Spotter</span></div><nav><a href="/sources">Sources</a><a href="/privacy">Privacy</a></nav></header>
 <main>
  <p className="eyebrow">Informational checklist · verified 16 August 2026</p>
  <h1>Spot governance questions before a campaign ships.</h1>
  <p className="lede">Choose the activation types in your campaign. This browser-local checklist returns issue-spotting prompts and official sources. It does not monitor feeds, determine compliance, score legal risk, or provide legal advice.</p>
  <section className="notice"><strong>Privacy boundary:</strong> entries and selections stay in this browser tab. They are not submitted to us. Do not enter confidential or privileged information.</section>
  <section className="panel" aria-labelledby="audit-heading"><h2 id="audit-heading">Campaign context</h2>
   <label htmlFor="industry">Client industry</label><select id="industry" value={industry} onChange={e=>setIndustry(e.target.value)}><option value="">Select industry…</option>{['Fashion & Luxury','Beauty & Personal Care','Entertainment & Media','Technology','Sports & Fitness','Food & Beverage','Financial Services','Health & Wellness','Retail & E-commerce'].map(x=><option key={x}>{x}</option>)}</select>
   <label htmlFor="description">Campaign description <span>(optional; remains in this tab)</span></label><input id="description" value={desc} onChange={e=>setDesc(e.target.value)} maxLength={300} placeholder="Brief non-confidential context"/>
   <fieldset><legend>Activation types</legend><div className="grid">{Object.entries(AUDIT).map(([k,v])=><label className={'check '+(checked.includes(k)?'active':'')} key={k}><input type="checkbox" checked={checked.includes(k)} onChange={()=>toggle(k)}/><span>{v.title}</span></label>)}</div></fieldset>
   <button className="primary" disabled={!industry} onClick={run}>Review selected areas</button>{!industry&&<p className="hint">Select an industry to continue.</p>}
  </section>
  {results&&<section aria-live="polite"><div className="resultHead"><div><p className="eyebrow">Issue-spotting output</p><h2>{results.length} review area{results.length===1?'':'s'}</h2></div><button className="secondary" onClick={clear}>Clear and start over</button></div>
   <p className="scope">Priorities are screening cues, not probability estimates or legal conclusions. Confidence: heuristic only; no facts, documents, jurisdictions, or current-law applicability were evaluated.</p>
   {results.map((f,i)=><article className="card" key={f.title}><div className="cardTitle"><h3>{f.title}</h3><span style={{background:color[f.priority][0],color:color[f.priority][1]}}>{f.priority} review priority</span></div><h4>Question to review</h4><p>{f.issue}</p><h4>Suggested next step</h4><p>{f.next}</p><h4>Official starting points</h4><ul>{f.sources.map(s=><li key={s}><a href={SOURCES[s].href} target="_blank" rel="noreferrer">{SOURCES[s].label}</a></li>)}</ul></article>)}
  </section>}
 </main>
 <footer><div><strong>RN Collins</strong><span>AI governance research and education</span></div><div><a href="mailto:collins.ra@northeastern.edu">Email</a><a href="https://linkedin.com/in/rn-collins" target="_blank" rel="noreferrer">LinkedIn</a><a href="/sources">Sources & limitations</a><a href="/privacy">Privacy</a></div></footer>
 <style jsx global>{`*{box-sizing:border-box}body{margin:0;background:${BG};color:${TX};font-family:Manrope,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:inherit}header{background:${G};color:white;padding:18px clamp(20px,5vw,48px);display:flex;justify-content:space-between;gap:24px;align-items:center}header div{display:flex;flex-direction:column;gap:3px}header span{font-size:12px;opacity:.72}nav,footer div:last-child{display:flex;gap:18px;flex-wrap:wrap}nav a,footer a{font-size:13px}main{width:min(860px,calc(100% - 40px));margin:auto;padding:64px 0 100px}.eyebrow{text-transform:uppercase;letter-spacing:.1em;font-size:11px;font-weight:700;color:${G}}h1{font-size:clamp(36px,7vw,64px);line-height:1.04;max-width:760px;margin:12px 0 20px}h2{font-size:26px}.lede{font-size:18px;line-height:1.7;max-width:720px;color:${MU}}.notice,.scope{padding:16px 18px;background:#E8F5F2;border:1px solid #c7dfda;border-radius:8px;line-height:1.6;margin:28px 0}.panel,.card{background:white;border:1px solid ${BD};border-radius:12px;padding:clamp(22px,5vw,40px);margin:28px 0}label,legend{font-size:13px;font-weight:700;display:block;margin:18px 0 8px}label span{font-weight:400;color:${MU}}select,input{width:100%;font:inherit;padding:13px 14px;border:1px solid ${BD};border-radius:7px;background:#fbfaf7}fieldset{border:0;padding:0;margin:22px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px}.check{display:flex;align-items:center;gap:10px;margin:0;padding:12px;border:1px solid ${BD};border-radius:7px;cursor:pointer}.check.active{border-color:${G};background:#E8F5F2}.check input{width:17px}.check span{color:${TX};font-size:13px}.primary,.secondary{font:inherit;font-weight:700;border-radius:7px;padding:13px 18px;cursor:pointer}.primary{width:100%;border:0;background:${G};color:white}.primary:disabled{opacity:.45;cursor:not-allowed}.secondary{background:transparent;border:1px solid ${BD}}.hint{text-align:center;font-size:12px;color:${MU}}.resultHead,.cardTitle,footer{display:flex;justify-content:space-between;align-items:center;gap:20px}.scope{background:#fff8e8;border-color:#ead9ab}.card h3{margin:0;font-size:19px}.cardTitle span{white-space:nowrap;border-radius:99px;padding:7px 10px;text-transform:uppercase;font-size:10px;font-weight:800;letter-spacing:.06em}.card h4{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:${MU};margin:22px 0 5px}.card p,.card li{line-height:1.65;font-size:14px}.card a{color:#0F5E50}footer{background:${TX};color:white;padding:30px clamp(20px,5vw,48px);flex-wrap:wrap}footer div:first-child{display:flex;flex-direction:column;gap:4px}footer span{font-size:12px;opacity:.6}@media(max-width:600px){header,.resultHead,.cardTitle{align-items:flex-start;flex-direction:column}.cardTitle span{white-space:normal}main{padding-top:42px}}`}</style></>
}